### ISSUE TITLE
Repository confusion

### ISSUE THREAD

**Issue by DanAmador** [Unity-Technologies/com.unity.uiwidgets#10]
Why are there two repositories for the same project? 
Is there a difference to the other [UIWidgets ](https://github.com/UnityTech/UIWidgets) repository ?

**Comment by kgdev** [comment]
This repo is for the next version of UIWidgets which is currently WIP. In the next version of UIWidgets, we will switch the rendering backend to Skia for better performance.

**Comment by ArEnSc** [comment]
Is this project still being worked on, it seems super useful @kgdev

**Comment by invlabz** [comment]
Hi I am planning to start a new project. What is your suggestion to use this awesome project or Unity built in UI?

**Comment by zhuxingwei** [comment]
Unity built-in UI (e.g., UGUI, UIKit) is OK for static and simple UIs inside most games (e.g., FPS, RTS, ACT, etc.). However, if your project needs fancy and dynamic UIs (e.g., a beautiful chat channel), or it is an UI driven project, UIWidgets would be a better choice

**Comment by invlabz** [comment]
@zhuxingwei Another question, I am trying to add Wordspace UI (button) attached to a cube. I can see UIWidgets, Cube and Button, but button do not get clicked. I guess interaction is consumed by UIWidgets. Is there any solution for it?
