### ISSUE TITLE
Colors are Washedout?

### ISSUE THREAD

**Issue by ArEnSc** [Unity-Technologies/com.unity.uiwidgets#109]
Hey so I am using the same color but it seems like the colours are washed out vs unity. The top is the unity color, the bottom is the color of the app bar, they are using the same color code.
[
<img width="70" alt="colorwashedout" src="https://user-images.githubusercontent.com/6252325/112511971-eb5c3e80-8d60-11eb-97b6-410f64166b68.PNG">
](URL)

I am going to try this with the original sample project and see if this is also a problem

**Comment by zhuxingwei** [comment]
Hi, thanks for the reporting ! 
Yes, it seems to be a bug. Could you please give us more information so that we can repro and fix it later, which may includes:
(1) the branch name that you use for the test
(2) the unity version
(3) the os type (windows, mac, etc.)
(4) a sample project (optional)

Thanks a lot !

**Comment by ArEnSc** [comment]
@zhuxingwei thanks for responding so quickly! yeah ill download the latest project and show you an example, @zhuxingwei also questions you guys are not abandoning this project right? let me know thanks!

**Comment by zhuxingwei** [comment]
yes, the team is working on some big changes on the project in the past 6 months, which mainly aims on runtime performance optimization.

btw, we are almost there and the first release will come out soon :-)

**Comment by ArEnSc** [comment]
So I checked this on Master and the problem isn't there
Is master stable? 
https://github.com/UnityTech/UIWidgets/

the problem is in release_1.5.4_stable it's in this branch

**Comment by zhuxingwei** [comment]
Yes, master is stable, you can use this branch for development
