### ISSUE TITLE
UIWidgets consumes events on World Space UI 

### ISSUE THREAD

**Issue by invlabz** [Unity-Technologies/com.unity.uiwidgets#111]
I am trying to add Wordspace UI (button) attached to a cube. I can see UIWidgets, Cube and Button, but button do not get clicked. I guess event is consumed by UIWidgets. Is there any solution for it?

**Comment by ArEnSc** [comment]
Hey, I am also experiencing this issue, when in release mode, cannot ray cast the scene it seems that UIWidgets eats all the events. I will provide a sample project. Is there a workaround to this? What file would I look into how the events are dispatched to the UIWidgets?

**Comment by zhuxingwei** [comment]
A UIWidgets panel behaves like a normal UI Panel in Unity, which consumes click events through callbacks like OnPointerDown, OnPointerUp. As the result, this issue might be more likely a UGUI problem than a UIWidgets problem, and solutions [here ](https://forum.unity.com/threads/blocking-physics-raycasts-with-the-ui.300157/)or [here ](https://answers.unity.com/questions/784617/how-do-i-block-touch-events-from-propagating-throu.html)could be helpful for you.

If you want to know how the pointer event handlers work in UIWidgets, the corresponding codes can be found at [here](https://github.com/Unity-Technologies/com.unity.uiwidgets/blob/uiwidget_1.0/com.unity.uiwidgets/Runtime/engine/UIWidgetsPanel.cs) and [here](https://github.com/Unity-Technologies/com.unity.uiwidgets/blob/master/com.unity.uiwidgets/Runtime/engine/UIWidgetsPanel.cs), for 1.0 and 2.0 respectively.

**Comment by ArEnSc** [comment]
@zhuxingwei thanks for the timely response I shall look into this
