### ISSUE TITLE
Inconsistent Stack widget performance

### ISSUE THREAD

**Issue by RF103T** [Unity-Technologies/com.unity.uiwidgets#148]
Unity Version: 2020.3.2f1c1
Parkage Version: UIWidgets 1.5.4-preview.12

When I use the Stack Widget like in flutter, I can't change the ```children``` property to update the z-order of the child widgets.

The following code can work in flutter, not work in UIWidgets.

我像 flutter 中那样使用 Stack widget 时，发现我不能动态修改```children```属性来改变子widget的前后顺序。

以下代码可以在flutter中实现效果，但在UIWidgets中没有效果。

flutter
```dart
class MyHomePage extends StatefulWidget {
  final String title;
  MyHomePage({Key? key, required this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var children = <Widget>[
    Positioned(
        top: 100,
        left: 100,
        child: Container(height: 100, width: 100, color: Colors.blue)),
    Positioned(
        top: 120,
        left: 120,
        child: Container(height: 100, width: 100, color: Colors.red))
  ];

  void _incrementCounter() {
    setState(() {
      var temp = children[0];
      children[0] = children[1];
      children[1] = temp;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(child: Stack(children: children)),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```
C#
```csharp
class MainUI : StatefulWidget
{
    public MainUI(Key key = null) : base(key) { }

    public override State createState()
    {
        return new MainUIState();
    }
}

class MainUIState: State<MainUI>
{
    int counter = 0;

    public override Widget build(BuildContext context)
    {
        List<Widget> widgets = new List<Widget>()
        {
            new Positioned(
            top: 100,
            left: 100,
            child: new Container(height : 100, width : 100, color : Colors.blue)),
            new Positioned(
            top: 120,
            left: 120,
            child: new Container(height : 100, width : 100, color : Colors.red))
        };

        return new ConstrainedBox(
            constraints: BoxConstraints.expand(),
            child: new Stack(
                children : new List<Widget>()
                {
                    new Column(
                            children: new List<Widget>()
                            {
                                new Expanded(
                                        child: new Row(
                                            crossAxisAlignment : CrossAxisAlignment.start,
                                            children : new List<Widget>()
                                            {
                                                new RaisedButton(
                                                    onPressed: () =>
                                                    {
                                                        this.setState(() =>
                                                        {
                                                            Widget temp = widgets[0];
                                                            widgets[0] = widgets[1];
                                                            widgets[1] = temp;
                                                        });
                                                    },
                                                    child : new Text("交换")
                                                )
                                            }
                                        )
                                    )
                            }
                        ),
                        new Stack(
                            children: widgets
                        )
                }
            )
        );
    }
}
```

**Comment by zhuxingwei** [comment]
Thanks for your feedback!

This issue should be caused by a minor mistake in your code. Since you recreate the `widgets` each time when building the widget, the state cannot be properly retained and changed between each interaction. You can fix it by moving the initiation of `widgets` outside the build function (a simple example is presented as follows):

```
class MainUI : StatefulWidget
{
    public MainUI(Key key = null) : base(key) { }

    public override State createState()
    {
        return new MainUIState();
    }
}

class MainUIState: State<MainUI>
{
    int counter = 0;
    
    List<Widget> widgets = new List<Widget>()
    {
        new Positioned(
            top: 100,
            left: 100,
            child: new Container(height : 100, width : 100, color : Colors.blue)),
        new Positioned(
            top: 120,
            left: 120,
            child: new Container(height : 100, width : 100, color : Colors.red))
    };

    public override Widget build(BuildContext context)
    {

        return new ConstrainedBox(
            constraints: BoxConstraints.expand(),
            child: new Stack(
                children : new List<Widget>()
                {
                    new Column(
                            children: new List<Widget>()
                            {
                                new Expanded(
                                        child: new Row(
                                            crossAxisAlignment : CrossAxisAlignment.start,
                                            children : new List<Widget>()
                                            {
                                                new RaisedButton(
                                                    onPressed: () =>
                                                    {
                                                        this.setState(() =>
                                                        {
                                                            Widget temp = widgets[0];
                                                            widgets[0] = widgets[1];
                                                            widgets[1] = temp;
                                                        });
                                                    },
                                                    child : new Text("交换")
                                                )
                                            }
                                        )
                                    )
                            }
                        ),
                        new Stack(
                            children: widgets
                        )
                }
            )
        );
    }
}
```

**Comment by RF103T** [comment]
> Thanks for your feedback!
> 
> This issue should be caused by a minor mistake in your code. Since you recreate the `widgets` each time when building the widget, the state cannot be properly retained and changed between each interaction. You can fix it by moving the initiation of `widgets` outside the build function (a simple example is presented as follows):
> 
> ```
> class MainUI : StatefulWidget
> {
>     public MainUI(Key key = null) : base(key) { }
> 
>     public override State createState()
>     {
>         return new MainUIState();
>     }
> }
> 
> class MainUIState: State<MainUI>
> {
>     int counter = 0;
>     
>     List<Widget> widgets = new List<Widget>()
>     {
>         new Positioned(
>             top: 100,
>             left: 100,
>             child: new Container(height : 100, width : 100, color : Colors.blue)),
>         new Positioned(
>             top: 120,
>             left: 120,
>             child: new Container(height : 100, width : 100, color : Colors.red))
>     };
> 
>     public override Widget build(BuildContext context)
>     {
> 
>         return new ConstrainedBox(
>             constraints: BoxConstraints.expand(),
>             child: new Stack(
>                 children : new List<Widget>()
>                 {
>                     new Column(
>                             children: new List<Widget>()
>                             {
>                                 new Expanded(
>                                         child: new Row(
>                                             crossAxisAlignment : CrossAxisAlignment.start,
>                                             children : new List<Widget>()
>                                             {
>                                                 new RaisedButton(
>                                                     onPressed: () =>
>                                                     {
>                                                         this.setState(() =>
>                                                         {
>                                                             Widget temp = widgets[0];
>                                                             widgets[0] = widgets[1];
>                                                             widgets[1] = temp;
>                                                         });
>                                                     },
>                                                     child : new Text("交换")
>                                                 )
>                                             }
>                                         )
>                                     )
>                             }
>                         ),
>                         new Stack(
>                             children: widgets
>                         )
>                 }
>             )
>         );
>     }
> }
> ```

Thanks for your reply! This example dose have a minor mistake. The following is the actual code where the problem occurred:

```csharp
    public class WindowsStackWidget : StatefulWidget
    {
        public WindowsStackWidget(Key key = null) : base(key) { }

        public override State createState()
        {
            return new WindowsStackState();
        }

        class WindowsStackState : State<WindowsStackWidget>
        {
            private List<Widget> windowWidgets;

            public WindowsStackState()
            {
                windowWidgets = new List<Widget>();
            }

            // ...

            // Use some ways to call
            public void CreateWindow(string name, Point position, Point size, Widget child)
            {
                Widget widget = windowWidgets.Find(widget => widget is ToolkitWindowWidget window && window.name == name);
                this.setState(() =>
                {
                    if (widget != default(Widget))
                        windowWidgets.Remove(widget);
                    windowWidgets.Add(new ToolkitWindowWidget(
                        name: name,
                        position: position,
                        size: size,
                        child: child
                    ));
                });
            }

            // Use some ways to call
            public void CloseWindow(string name)
            {
                Widget widget = windowWidgets.Find(widget => widget is ToolkitWindowWidget window && window.name == name);
                if (widget != default(Widget))
                {
                    this.setState(() =>
                    {
                        windowWidgets.Remove(widget);
                    });
                }
            }

            // Use some ways to call
            public void StickWindow(string name)
            {
                if (windowWidgets[windowWidgets.Count - 1] is ToolkitWindowWidget window && window.name != name)
                {
                    int windowIndex = windowWidgets.FindIndex(widget => widget is ToolkitWindowWidget window && window.name == name);
                    if (windowIndex != -1)
                    {
                        this.setState(() =>
                        {
                            Widget temp = windowWidgets[windowWidgets.Count - 1];
                            windowWidgets[windowWidgets.Count - 1] = windowWidgets[windowIndex];
                            windowWidgets[windowIndex] = temp;
                        });
                    }
                }
            }

            public override Widget build(BuildContext context)
            {
                return new Stack(
                    children: windowWidgets
                );
            }
        }
    }
```

I don't think it recreated `windowWidgets`. But I can't change the z-index of `ToolkitWindowWidget`. When it tried to remove a window widget, it will remove the wrong widget.
By the way, `CloseWindow` and `StickWindow` methods are called inside `ToolkitWindowWidget`. So, these problems may be about widget context?

**Comment by zhuxingwei** [comment]
Since the code you provide is not complete, I cannot figure out what goes wrong here. However, maybe you can debug your code a bit on:
(1) is the `setState` callbacks are correctly called when `StickWindow` or `CloseWindow` is called
(2) look into how the `windowWidgets` look like when the `build` method is called, is it properly updated ?

Hope this will help you to solve the problem !

**Comment by RF103T** [comment]
> Since the code you provide is not complete, I cannot figure out what goes wrong here. However, maybe you can debug your code a bit on:
> (1) is the `setState` callbacks are correctly called when `StickWindow` or `CloseWindow` is called
> (2) look into how the `windowWidgets` look like when the `build` method is called, is it properly updated ?
> 
> Hope this will help you to solve the problem !

Thanks for your advice! I already had used `Overlay` to solve the problem. It suits my needs better.
