### ISSUE TITLE
Error java.lang.ClassNotFoundException: com.unity.uiwidgets.plugin.UIWidgetsMessageManager

### ISSUE THREAD

**Issue by piotrszpruta** [Unity-Technologies/com.unity.uiwidgets#186]
While deploying project to device or simulator, I see plain white screen and adb logs looks basically like this

```
06-30 12:08:47.799  6708  6724 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.unity.uiwidgets.plugin.UIWidgetsMessageManager
06-30 12:08:47.799  6708  6724 E Unity   : java.lang.ClassNotFoundException: com.unity.uiwidgets.plugin.UIWidgetsMessageManager
06-30 12:08:47.799  6708  6724 E Unity   :      at java.lang.Class.classForName(Native Method)
06-30 12:08:47.799  6708  6724 E Unity   :      at java.lang.Class.forName(Class.java:400)
06-30 12:08:47.799  6708  6724 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
06-30 12:08:47.799  6708  6724 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source)
06-30 12:08:47.799  6708  6724 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
06-30 12:08:47.799  6708  6724 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:98)
06-30 12:08:47.799  6708  6724 E Unity   :      at android.os.Looper.loop(Looper.java:154)
06-30 12:08:47.799  6708  6724 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
06-30 12:08:47.799  6708  6724 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.unity.uiwidgets.plugin.UIWidgetsMessageManager" on path: DexPathList[[zip file "/data/app/com.DefaultCompany.iHelpAr-1/base.apk"],nativeLibraryDirectories=[/data/app/com.DefaultCompany.iHelpAr-1/lib/arm, /data/app/com.DefaultCompany.iHelpAr-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
06-30 12:08:47.799  6708  6724 E Unity   :      at dalvik.system.BaseD

```

Project running in unity is working fine. Does someone encountered that problem?

**Comment by zhuxingwei** [comment]
Thanks a lot for the report !

First, since you are using uiwidgets_1.0, please check whether the file "UIWidgetsMessageManager.java" exists under this path /YOUR_PACKAGE_PATH/com.unity.uiwidgets/Runtime/Plugins/platform/android.

If it exists, please then check this file (i.e., UIWidgetsMessageManager.java) within the exported gradle project.

**Comment by piotrszpruta** [comment]
I've checked in ```/Packages/com.unity.uiwidgets/Runtime/Plugins/platform/android``` and ```UIWidgetsMessageManager.java``` exists there, but where I should be looking to check within the exported gradle project? I've opened apk with 7zip and it wasn't there (I'm still learning sorry)

**Comment by zhuxingwei** [comment]
Thanks for the response !

To export a gradle project, you should pick "Export Project" in the Build Settings.
<img width="686" alt="WeChatba6e81fa6487a6d8c03e63224bfc31e5" src="https://user-images.githubusercontent.com/4134652/124061811-28bc2080-da62-11eb-944a-3c5b54eff723.png">

Then you can use android studio to open the project and try to find the .java files here.
<img width="786" alt="WeChat7709a58ccb900ca300a8aad70573a4d5" src="https://user-images.githubusercontent.com/4134652/124061912-5b661900-da62-11eb-8038-9414669a00ee.png">

btw, I am using Unity 2019.4.26f1 and you may give it a try?

**Comment by piotrszpruta** [comment]
Hey, I'm also using 2019.4.26f1, folder ```unity.uiwidgets.plugin``` is not appearing there.

**Comment by piotrszpruta** [comment]
Same is happening for unity 2019.4.28f1, I don't have an idea what i could do now

**Comment by zhuxingwei** [comment]
ok, so the problem seems to be that Unity fails to pack our native plugin (i.e., stuffs inside unity.uiwidgets.plugin/ ) into the android project. Currently not clear about how it may happen, but you may want to check:

(1) use the latest uiwidgets_1.0 branch by cloning our repo and checking out the specific branch;
(2) open the UIWidgetsSample project in our repo and use a sample scene inside;
(3) export the project as I suggested above;
(4) open the exported project using Android studio and see whether the plugin is correctly installed

If it still doesn't work, you can send us your sample project so that we can test on it and figure out the problem

**Comment by piotrszpruta** [comment]
about first, i've cloned uiwidgets_1.0 but i couldn't get it to work, then i updated it thought package manager to ```preview.12``` before i had opened issue but i've closed it because updating solved it. I've builded Todo app and it runs fine, in sample project theres ```preview.1``` idk why is there such difference

**Comment by piotrszpruta** [comment]
After upgrading sample project ```uiwidgets_1.0.preview.1``` to ```preview.12``` same problem

**Comment by zhuxingwei** [comment]
The uiwidgets package in package manager is deprecated. Please use uiwidgets_1.0 branch in this repo. If uiwidgets_1.0 doesn't work, please tell us what happened (e.g., some error messages) together with a reproduction environment, e.g., platform, unity version, etc.

Thanks !

**Comment by piotrszpruta** [comment]
Okay so I should open new issue right now?

**Comment by zhuxingwei** [comment]
Yes. Thanks!
