### ISSUE TITLE
Shader error failed to open source file

### ISSUE THREAD

**Issue by piotrszpruta** [Unity-Technologies/com.unity.uiwidgets#192]
Environment:
Unity: 2019.4.28f1
Package: straight from github uiwidgets_1.0

Reproduction steps:
create new project
import uiwidgets_1.0 from github

After importing package to unity project, I've got pink screen with following errors:
![obraz](https://user-images.githubusercontent.com/38475451/124246012-d130ba00-db20-11eb-987b-aa8f25584ec9.png)

Those files exists in ```\Packages\com.unity.uiwidgets\com.unity.uiwidgets\Runtime\Resources\shaders\```

**Comment by zhuxingwei** [comment]
Hi, sorry for the late response!

We have tried to follow your reproduction steps but no error message comes up. Could you please give us more info to address this problem:
(1) how did you import uiwidgets package from github?
(2) what is your os (mac or windows?)
(3) what is the target platform (android?)

Thanks !

**Comment by piotrszpruta** [comment]
Sure

Host: Windows
Target: Android

I've downloaded uiwidgets_1.0 with ''' git clone https://github.com/Unity-Technologies/com.unity.uiwidgets.git --branch uiwidgets_1.0'''

**Comment by zhuxingwei** [comment]
Hi, I have tried again according to your reproduction environment but still no error bumps out. Could you please share us your project (or a minimum MVP to reproduce the errors) ? Thanks !

**Comment by piotrszpruta** [comment]
Path in my opinion is fine ```F:\ihelpar\Packages\com.unity.uiwidgets\com.unity.uiwidgets``` its in two folders because first one is with Samples

Can I upload it to google drive or smth because I cant add zip there and i cant push to github because there are large files (lol)

**Comment by zhuxingwei** [comment]
github is ok. Thanks!

**Comment by piotrszpruta** [comment]
i cant push to github so im sending it on google drive 

[link](https://drive.google.com/file/d/1MmbW7qasllszcDQmtrQi1ItxJwlhPeOP/view?usp=sharing)

**Comment by zhuxingwei** [comment]
Thanks and I will look into it later.

**Comment by zhuxingwei** [comment]
Hi I have tried your demo project and reproduced the shader error. By now I still cannot figure out what is happening :(. 

However, I have tried to open the sample project under com.unity.uiwidgets/Samples/ and it works fine, so I am sure the problem should be somewhere inside your demo project. Yet I need more time to investigate it and will let you know when I have any progress.

For a quick work-around, maybe you can start your job using our sample project by adding your uiwidgets panel classes there.

Cheers!

**Comment by zhuxingwei** [comment]
Hi @piotrszpruta

The problem is that, you cannot clone the uiwidgets repo directly to the Packages folder of your project since Unity will treat any folder there as a local package: however, com.unity.uiwidgets itself is not a package (the package is com.unity.uiwidgets/com.unity.uiwidgets), therefore Unity will be confused when collecting build-in resources for it.

To fix this issue, please move com.unity.uiwidgets into somewhere different (e.g., YouProjectPath/thirdparty/com.unity.uiwidgets) and add reference to it using package manager. Then reimport all and things will work.

**Comment by piotrszpruta** [comment]
Ohh okay I get it now, interesting I didn't saw any info about that anywhere. Thank you so much I can finally work on my app :D
