### ISSUE TITLE
使用IL2CPP编译会导致空场景

### ISSUE THREAD

**Issue by ListenPlum** [Unity-Technologies/com.unity.uiwidgets#195]
![48a78e0462eac8ccd31b29503fd095c](https://user-images.githubusercontent.com/34758510/125056119-7e37a380-e0da-11eb-8f43-28abd36a5d9d.png)

**Comment by zhuxingwei** [comment]
Hi thanks for the reporting !

We are looking into it and will let you know when the bug is fixed

**Comment by guanghuispark** [comment]
Hi @ListenPlum, this bug has been fixed #200

**Comment by ListenPlum** [comment]
Android 端还有这个问题

**Comment by zhuxingwei** [comment]
Hi Thanks for the reporting!

We have tested on android (both mono and il2cpp) but cannot reproduce this issue. 

Please make sure that your build settings is armv7 and graphic api is opengles 3.0/2.0. Currently uiwidgets 2.0 doesn't support arm64 or vulkan.

Thanks!

**Comment by ListenPlum** [comment]
Okay, I've solved this problem. Thank you

**Comment by baoxiehao** [comment]
> Hi Thanks for the reporting!
> 
> We have tested on android (both mono and il2cpp) but cannot reproduce this issue.
> 
> Please make sure that your build settings is armv7 and graphic api is opengles 3.0/2.0. Currently uiwidgets 2.0 doesn't support arm64 or vulkan.
> 
> Thanks!

Support arm64 now？

**Comment by zhuxingwei** [comment]
Yes, Android arm64 is supported already

**Comment by baoxiehao** [comment]
> Yes, Android arm64 is supported already

But run on real android device shows grey page，almost dark

**Comment by baoxiehao** [comment]
> > Yes, Android arm64 is supported already
> 
> But run on real android device shows grey page，almost dark

use ELGS is OK now! btw, any wechat group?
