### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Leacae** [Unity-Technologies/com.unity.uiwidgets#196]
Hi, the following error occurred during the process of building the apk 

![testaaa](https://user-images.githubusercontent.com/19548245/125110679-79451500-e117-11eb-82ad-137d4dfb9722.png)

**Comment by zhuxingwei** [comment]
Hi, thanks for the reporting !

UIWidgets only support armv7 for now. Please don't build arm64 or x86(for emulator).

btw, please include the following info so that we can help you find the problem more quickly:
(1) Your Unity version
(2) Your uiwidgets version
(3) Your Host platform

Thanks !

**Comment by Leacae** [comment]
Hello, I encountered an error during the process of importing   uiwidgets in a new project

Set up:
Windows 11,
Unity 2019.4.28f1c1,
com.unity.uiwidgets  github master branch

This is my new project recording file:
![屏幕截图 2021-07-15 032938](https://user-images.githubusercontent.com/19548245/125681530-0b3c6c80-b3e1-4a58-8120-8e85e355802d.png)


https://user-images.githubusercontent.com/19548245/125681422-39c0d9a0-7710-46d1-928f-3526344dc3d4.mp4

**Comment by zhuxingwei** [comment]
Hi Thanks for the reporting !

I have just tested on Windows 10 with the latest uiwidgets and Unity 2019.4.28f1c1 following the steps in your record and cannot reproduce the error.

However, according to your report earlier, it seems that the import process used to be ok? If it is true, could you please inform us the following information to help us diagnosing this issue:
(1) what is the difference between the two setups (i.e., the "failed to build apk" one and the "failed to import" one) ?
(2) will the issue fixed after updating uiwidgets to the latest version and doing a re-import ?
(3) can you show us a snapshot of the inspector window of the file UIWidgets/Runtime/Plugins/x86_64/libUIWidgets.dll ?

Thanks !

**Comment by Leacae** [comment]
Sorry, I am using window11 now. I upgraded the operating system to window11 before. Could this error be related to window11?

This is my libUIWidgets.dll inspector(I didn’t change the default settings )：
![屏幕截图 2021-07-15 174941](https://user-images.githubusercontent.com/19548245/125768194-472200f1-e228-4ca5-8dec-8b77b485c896.png)

**Comment by zhuxingwei** [comment]
According to the information we have, it might be relevant to windows 11. I will try to get a windows 11 pc later and have a try. 

As a work around, you can try uiwidgets 1.0 for now and transfer back to uiwidgets 2.0 when this issue is fixed. The transfer will be very simple unless you project is really huge.

**Comment by Leacae** [comment]
Thank you. Maybe I shouldn't upgrade to windows 11. Maybe I should go back to windows 10

**Comment by Leacae** [comment]
Thank you. Maybe I shouldn’t   upgrade to windows 11. Maybe I should roll back the version to windows 10. I hope uiwidgets can support Windows 11. Thank you for your efforts.
