### ISSUE TITLE
2.0.3 Release package contains LFS pointer file instead of actual binary

### ISSUE THREAD

**Issue by FrankNine** [Unity-Technologies/com.unity.uiwidgets#205]
Hello,

I just downloaded the latest 2.0.3 release zip and tried to import content of `com.unity.uiwidgets` into my project. When it tried to push to my repository I got an LFS error. It seems following files are packed as LFS pointer files instead of actual binaries
```
Assets/Runtime/Plugins/ios/libUIWidgets.a
Assets/Runtime/Plugins/Android/libUIWidgets.so
Assets/Runtime/Plugins/osx/libUIWidgets.dylib
Assets/Runtime/Plugins/x86_64/libUIWidgets.dll 
```

Thank you.

**Comment by guanghuispark** [comment]
Hi, thinks for your feedback! You can use `git clone git@github.com:Unity-Technologies/com.unity.uiwidgets.git` to get those actual binary files

**Comment by zhuxingwei** [comment]
You can also try `git lfs fetch` to get the actual binaries from the pointer files
