### ISSUE TITLE
Is _pageController?.dispose(); missing here?

### ISSUE THREAD

**Issue by MobilEKG** [Unity-Technologies/com.unity.uiwidgets#219]
https://github.com/Unity-Technologies/com.unity.uiwidgets/blob/ac88cc8a69bc0e4149f62790212196926ef69ec7/com.unity.uiwidgets/Runtime/material/tabs.cs#L1051

```
public override void dispose() {
    if (_controllerIsValid) {
        _controller.animation.removeListener(_handleTabControllerAnimationTick);
    }

    _controller = null;
    
    _pageController?.dispose(); // Should be here?

    base.dispose();
}
```

**Comment by zhuxingwei** [comment]
Hi, thanks a lot for the reporting !

According to my understanding, although the  _pageController is created and owned by the TabBarViewState, it is handed to a PageView and works as a part of it then. The PageView will determine its role and state in the Widget tree and detach it if it is not used anymore. As the result, we don't need to dispose it here.

Please correct me if there is anything wrong in my explanation. Thanks a lot !
