### ISSUE TITLE
RenderParagraph._layoutChildren似乎存在数组越界?

### ISSUE THREAD

**Issue by zhiyangyou** [Unity-Technologies/com.unity.uiwidgets#228]
![image](https://user-images.githubusercontent.com/70576712/129709158-415ca4ee-afd3-437e-b97c-28ab26d46260.png)
版本:master分支最新提交节点

**Comment by zhuxingwei** [comment]
Hi Thanks for the reporting !

Good Catch! 

Yes, it seems to be a bug. We will investigate it now and fix it soon.

**Comment by zhiyangyou** [comment]
好的,收到,谢谢!

**Comment by zhuxingwei** [comment]
fixed in #230

**Comment by zhiyangyou** [comment]
谢谢.
