### ISSUE TITLE
ParagraphBuilder.addPlaceholder断言可能存在问题?

### ISSUE THREAD

**Issue by zhiyangyou** [Unity-Technologies/com.unity.uiwidgets#231]
![lQLPDhqYrROJVoXNA-HNBkawqu7bldUKGl4cQGXtd4MHWw_1606_993](https://user-images.githubusercontent.com/70576712/129826820-5bdbe5ba-4250-4110-9465-bd096d388ec4.png)

UIWidgets使用版本 : master分支最新节点
触发条件 : 当alignment=PlaceholderAlignment.top , baseline=TextBaseline.alphabetic  发生断言失败

参考flutter 1.17.0-dev.5.0,这边的断言写法如图

**Comment by zhiyangyou** [comment]
![image](https://user-images.githubusercontent.com/70576712/129830866-47c02867-44ac-4089-8e70-66b131e429b9.png)
UIWidgets使用版本 : master分支最新节点
 参考flutter 1.17.0-dev.5.0,这边的断言写法如图

**Comment by zhiyangyou** [comment]
> ![image](https://user-images.githubusercontent.com/70576712/129830866-47c02867-44ac-4089-8e70-66b131e429b9.png)
> UIWidgets使用版本 : master分支最新节点
> 参考flutter 1.17.0-dev.5.0,这边的断言写法如图

**Comment by zhiyangyou** [comment]
![image](https://user-images.githubusercontent.com/70576712/129831280-066499d6-dc41-4a94-ac06-22fe7d156025.png)
UIWidgets使用版本 : master分支最新节点
触发条件 : widget重建
参考flutter 1.17.0-dev.5.0, compareTo写法如截图

**Comment by zhiyangyou** [comment]
谢谢, 看到master分支已经提交了相应的fix.

**Comment by zhuxingwei** [comment]
Thanks for your reporting !
