### ISSUE TITLE
Unity 2020?

### ISSUE THREAD

**Issue by EmElleE** [Unity-Technologies/com.unity.uiwidgets#254]
Hey I saw in an issue you only support 2019 unity as well ... you only support the CN version?

**Comment by zhuxingwei** [comment]
Hi @pajama , Thanks for the kind help!

UIWidgets is not a common 3rd party plugin for Unity, but a 1st party plugin, which means that it requires many modifications on the Unity Engine itself. 

Currently the dev team of Unity China is responsible for this plugin so we can add those necessary modifications to Unity CN versions only. Though we are still in a long discussion with other teams on the progress of merging UIWidgets to the general Unity versions.

If you want to contribute to this project, please give it a try and use it to build something (big :-)) in your everyday work. We believe that it would make the merging progress much faster if UIWidgets can be proven useful for more and more Unity developers.

**Comment by zhuxingwei** [comment]
Unity 2020.3LTS is now eventually supported on UIWidgets 2.0.4
