### ISSUE TITLE
TextField immediately dismisses keyboard

### ISSUE THREAD

**Issue by paulio** [Unity-Technologies/com.unity.uiwidgets#262]
I have a very simple TextField. In an Android build when I tap the text field you see the keyboard flicker and then vanish. If you're lucky it will take and you can enter values. I have the same behaviour in the Unity Editor if I left-click the text. However, if I right-click it works perfectly. Unity 2019.4.4f1, UIWidgets preview 12 1.5.4

**Comment by zhuxingwei** [comment]
Hi Thanks for the feedbacks !

UIWidgets preview 12 in the Unity package manager is not the latest version of uiwidgets 1.5.4 and may contain bugs. Please try fetch the latest uiwidgets 1.5.4 by cloning the repo from github and then checkout the `uiwidgets_1.0` branch.

Thanks !

**Comment by paulio** [comment]
Thanks for the comment but I'm not sure what you're asking me to do. I've fetched the uiwidgets_1.0 branch but the package.json is still staying the latest is preview 12. What steps should I be taking after fetching the branch?

**Comment by paulio** [comment]
I'm closing the issue because I believe it's caused with a clash with the MRTK toolkit. It might be good to look at it further but it's not a general problem.
