### ISSUE TITLE
2.0.3分支上UIWidgetsSamples_2019_4在Android上运行黑屏

### ISSUE THREAD

**Issue by tomcatter** [Unity-Technologies/com.unity.uiwidgets#265]
你好，我使用2.0.3分支中的UIWidgetsSamples_2019_4在Android中运行，只有unity logo出现，然后就一直黑屏了，使用1.x的版本可以在android上运行。

**Comment by zhuxingwei** [comment]
Hi 多谢您的反馈！

烦请您告诉我们一下您使用的Unity版本，Android手机信息（机型，SDK版本号），构建方法（il2cpp或mono，Graphic API类型）以便我们排查问题。

从您目前反馈的情况上看，问题很大可能是您构建时选择了我们暂时不支持的Graphic API（Vulkan）。烦请您检查一下，确保您构建时选择的是优先使用GLES。
![image](https://user-images.githubusercontent.com/4134652/142091040-87a2695e-70aa-4a43-9a50-afa452728006.png)

谢谢！

**Comment by tomcatter** [comment]
@zhuxingwei 我使用的是Unity 2019.4.32f1c1版本，是由于Graphics API引起的，默认是选用的Vulkan优先，改成OpenGLES3能运行正常了。

其他配置如下：
![0211117105715](https://user-images.githubusercontent.com/7018011/142125421-93841291-06a3-4d36-86dc-2c6d32cd72f8.png)

安装的设备是华为metapadpro12.6。

另外，还有一个问题，看介绍之前是有一个微信的技术交流群的，不知道现在还能不能加入，我们团队计划在项目上接入UIWidgets这个库，希望能找到一个交流讨论的地方。非常感谢

**Comment by zhuxingwei** [comment]
Hi 您好，你试试扫一下这个群名片加入即可：

![331637118547_ pic](https://user-images.githubusercontent.com/4134652/142127572-824ce092-1b78-4cf5-bab7-33b8236284fe.jpg)

**Comment by tomcatter** [comment]
@zhuxingwei OK，我加入了，感谢！
