### ISSUE TITLE
TextFormField组件限制输入字符和长度失效

### ISSUE THREAD

**Issue by tomcatter** [Unity-Technologies/com.unity.uiwidgets#269]
代码如下：
```
 new TextFormField(
                    maxLines:1,
                    onSaved: (value)=>{ },
                    controller: this._phoneEditingController,
                    textAlign: TextAlign.left,
                    inputFormatters: new List<Unity.UIWidgets.service.TextInputFormatter>{
                           WhitelistingTextInputFormatter.digitsOnly, new LengthLimitingTextInputFormatter(6)
                     },
                     decoration: new InputDecoration(
                            hintText:"请输入验证码",
                            contentPadding: EdgeInsets.only(top: 0, bottom: 0),
                            hintStyle: new TextStyle(color: new Color(0xFF999999), fontSize: 13),
                            alignLabelWithHint: true,
                            border: new OutlineInputBorder(borderSide: BorderSide.none)
                            )
                    )
```
另外还有一个问题，在安卓上面输入提示符显示特别巨大

![微信图片_20211130204758](https://user-images.githubusercontent.com/7018011/144050078-73d2efb3-cab6-4840-ad3f-4ab0d70c6fe4.jpg)

运行环境：Unity 2019.4.32f1c1  
                  UIWidgets 2.0.3

**Comment by tomcatter** [comment]
我使用master最新的代码，输入限制这个问题解决了，但是选中输入框的内容的这个显示还是不正确

**Comment by zhuxingwei** [comment]
嗯嗯多谢您的反馈！

您指的“选中输入框的内容的这个显示还是不正确” 是指什么？从您的截图上看是那个液滴状的提示符的大小有问题吗？还是说还有别的问题？

确定问题后我们会尽快排查修复。谢谢！

**Comment by tomcatter** [comment]
@zhuxingwei 对，就是这个提示符特别大

**Comment by SiyaoHuang** [comment]
@tomcatter 目前还在寻找bug的真正原因。紧急修复的话可以看这个 [commit](https://github.com/Unity-Technologies/com.unity.uiwidgets/commit/cb3871d0d90c8af13d1f93d32b9d73c0f7e6a91b)

**Comment by tomcatter** [comment]
@SiyaoHuang 不是特别紧急，我先按这个commit的修改看看效果

**Comment by SiyaoHuang** [comment]
@tomcatter 嗯嗯，换一个加个`Stack`，相对`0，0` 的`Positioned`合理一点。这个是[PR](https://github.com/Unity-Technologies/com.unity.uiwidgets/pull/270)。明天再看看有其他方法吗。

**Comment by tomcatter** [comment]
@SiyaoHuang 按照 这个[commit](https://github.com/Unity-Technologies/com.unity.uiwidgets/commit/cb3871d0d90c8af13d1f93d32b9d73c0f7e6a91b) 修改以后提示符大小变小了，位置有些不正确。如下图
![Uploading 11202111452.jpg…]()

再加上这个[PR](https://github.com/Unity-Technologies/com.unity.uiwidgets/pull/270)的修改，显示还是如上图

**Comment by SiyaoHuang** [comment]
@tomcatter 还在位移的原因中。过程中还发现多行选中，会出现右边handle固定在左上角。这个宽度是来自handle的宽度
[原本的](https://github.com/Unity-Technologies/com.unity.uiwidgets/blob/492ce5a3ed83081d25a47aba1570830400e9bd1f/com.unity.uiwidgets/Runtime/material/text_selection.cs#L653-L662) 改成
```
public override Offset getHandleAnchor(TextSelectionHandleType type, float textLineHeight) {
      return Offset.zero;
}
```

**Comment by SiyaoHuang** [comment]
> @tomcatter 还在位移的原因中。过程中还发现多行选中，会出现右边handle固定在左上角。这个宽度是来自handle的宽度 [原本的](https://github.com/Unity-Technologies/com.unity.uiwidgets/blob/492ce5a3ed83081d25a47aba1570830400e9bd1f/com.unity.uiwidgets/Runtime/material/text_selection.cs#L653-L662) 改成
> 
> ```
> public override Offset getHandleAnchor(TextSelectionHandleType type, float textLineHeight) {
>       return Offset.zero;
> }
> ```
原因找到，engine（c++）部分，传递的数组长度机算出错。

**Comment by tomcatter** [comment]
@SiyaoHuang 这个修改什么时候同步到master分支呢

**Comment by SiyaoHuang** [comment]
> @SiyaoHuang 这个修改什么时候同步到master分支呢

@tomcatter merge好了，你试一下

**Comment by tomcatter** [comment]
> > @SiyaoHuang 这个修改什么时候同步到master分支呢
> 
> @tomcatter merge好了，你试一下

正常了
