### ISSUE TITLE
DropdownButtonFormField 无法设置高度

### ISSUE THREAD

**Issue by tomcatter** [Unity-Technologies/com.unity.uiwidgets#278]
使用`SizeBox` 约束`DropdownButtonFormField`，显示不正确，代码如下：
```
                    new SizedBox(
                        width: 200,
                        height: 30,
                        //child: new Center(
                        child: new DropdownButtonFormField<string>(
                            value: "USA",
                            decoration : new InputDecoration(
                                enabledBorder:new OutlineInputBorder(
                                    borderSide:new  BorderSide(color: Color.fromRGBO(155, 244, 255, 1), width: 1),
                                    borderRadius: BorderRadius.circular(5)
                                    ),
                                border: new OutlineInputBorder(
                                    borderSide: new BorderSide(color:Colors.red, width: 1f),
                                    borderRadius: BorderRadius.circular(5)
                                    ),
                                filled: true,
                                fillColor: Color.fromRGBO(218, 251, 255, 0.3f)
                                ),
                            onChanged: (v) =>
                            {
                            },
                            items: menuItems
                            )
                        )
```
效果图：

![11215171220](https://user-images.githubusercontent.com/7018011/146157521-2d30f121-62b3-442a-b4d3-046132298693.png)

当我注释掉`SizeBox`的`height`属性后，如下图：
![211215171412](https://user-images.githubusercontent.com/7018011/146157739-b284b7cf-0d34-4550-a11d-5b0117b254e6.png)

`DropdownButtonFormField ` 类里也没有发现有高度相关的属性，所以正确的设置`DropdownButtonFormField `的方法是什么？

**Comment by zhuxingwei** [comment]
Hi Thanks for the report!

Please refer to this link which provides several solutions to fix a similar problem of yours: https://stackoverflow.com/questions/53983783/set-height-of-dropdownbuttonformfield-list

**Comment by tomcatter** [comment]
@zhuxingwei 这个链接里的内容我看了的，`UIWidgets`里面的`DropdownButtonFormField` 没有`height`这个属性可以设置。现在我自己实现了一个`Dropdown`

**Comment by zhuxingwei** [comment]
Hi Thanks for the reply!

Yes, the latest UIWidgets 2.0 is transferred from flutter 1.17.5 in which `DropdownButtonFormField`  doesn't have the property `height` yet. 

However, we are planing to do an upgrade to flutter 2.0 (in which this property exists) in 2022. But if you really need this property urgently,  maybe you can implement this `property` by backporting it from flutter 2.0.

**Comment by tomcatter** [comment]
@zhuxingwei 好的，我暂时用自定义的来代替
