### ISSUE TITLE
Use external Texture in 2.0

### ISSUE THREAD

**Issue by garsonlab** [Unity-Technologies/com.unity.uiwidgets#283]
`new Texture(textureId: UnityEngine.RenderTexture.GetNativeTexturePtr().ToInt32())` is  not display in my project.  And is there a way to show NV12 or custom material combined texture

**Comment by zhuxingwei** [comment]
Hi thanks a lot for the report!

Currently `Texture` is not fully supported in UIWidgets 2.0 yet so we didn't merge this feature into master. Specifically, you can try this working branch `siyaoH/1.17externalTexture` for a quick preview.

If your project need this feature urgently, please try UIWidgets 1.0 instead which fully support the feature of external `Texture`.

**Comment by zhuxingwei** [comment]
This feature is now partially implemented by #340 . Please read this [documentation](https://github.com/Unity-Technologies/com.unity.uiwidgets#show-external-texture) for the details.
