### ISSUE TITLE
.9.png format of a image

### ISSUE THREAD

**Issue by tomcatter** [Unity-Technologies/com.unity.uiwidgets#292]
I refer to this [link](https://stackoverflow.com/questions/48056304/how-to-display-9-png-format-of-a-picture-in-flutter) to use `.9.png`  image, but the display is not correct.

as shown blow:
![11223101050](https://user-images.githubusercontent.com/7018011/147177006-aa03803e-abab-494b-8d17-576b51075999.png)

the image of resource used blow:
![panel_bg 9](https://user-images.githubusercontent.com/7018011/147177171-fd3cfd30-078b-4bd8-8895-65090ea04d87.png)

**Comment by zhuxingwei** [comment]
Thanks for the reporting!

The team is currently on vacation and we will look into this issue asap when we are back !

**Comment by zhuxingwei** [comment]
Sorry that I cannot reproduce your results in my repo. Please refer to #297 for my test sample and look forward to your further feedbacks

**Comment by tomcatter** [comment]
I misunderstood the use of the API, I tryed a few times and find the parameters that display correctly.
