### ISSUE TITLE
Does uiwidgets support WebviewScaffold  

### ISSUE THREAD

**Issue by 510074793** [Unity-Technologies/com.unity.uiwidgets#295]
Does uiwidgets support WebviewScaffold

**Comment by zhuxingwei** [comment]
Hi thanks for the question !

`WebviewScaffold` looks like a webview plugin for flutter which also includes native codes on iOS and Android. 

Currently UIWidgets doesn't support this feature yet, but it should be possible to be transferred from flutter: (1) the dart part can be translated to C# directly; (2) the native part can be added to UIWidgets engine or Unity as a native plugin.

Though our team cannot include this feature into our short-term roadmap by now, we are always willing to help if you want to give it a try.
