### ISSUE TITLE
打开就报错

### ISSUE THREAD

**Issue by daimou** [Unity-Technologies/com.unity.uiwidgets#321]
Failed to load 'F:/Work/Unity/UIWidget/com.unity.uiwidgets-master/com.unity.uiwidgets/Runtime/Plugins/x86_64/libUIWidgets.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.

**Comment by zhuxingwei** [comment]
Hi Thanks for your reporting !

Please kindly refer to the 2nd question in our [FAQ](https://github.com/Unity-Technologies/com.unity.uiwidgets#faq). The corresponding solution might help you fix this issue. Feel free to contact us for further feedback !
