### ISSUE TITLE
M1 pro的mac导入2.0报错，unity使用的2020.3.35f1c1 intel版

### ISSUE THREAD

**Issue by xuexirong** [Unity-Technologies/com.unity.uiwidgets#337]
NullReferenceException: Object reference not set to an instance of an object
Unity.UIWidgets.engine.UIWidgetsPanelWrapper.Destroy () (at Packages/com.unity.uiwidgets/com.unity.uiwidgets/Runtime/engine/UIWidgetsPanelWrapper.cs:327)
Unity.UIWidgets.engine.UIWidgetsPanel.OnDisable () (at Packages/com.unity.uiwidgets/com.unity.uiwidgets/Runtime/engine/UIWidgetsPanel.cs:379)

**Comment by xuexirong** [comment]
开发人员现在用M1开发的非常多  请尽快更新m1版本 谢谢

**Comment by zhuxingwei** [comment]
Thanks for the feedback!

Yes the M1 support is in our dev plan and still in progress, we will be glad to let you know when it is ready !

**Comment by xuexirong** [comment]
@zhuxingwei 有没有官方微信群  可以拉我进去么

**Comment by zhuxingwei** [comment]
Sure, this is our official QQ Group: UIWidgets (Group ID: 234207153)

**Comment by zhuxingwei** [comment]
Sorry for the late response!

After some investigation, we have concluded that: 
(1) a native M1 support can only be done after an overall upgrade to flutter engine 3 (e.g., https://github.com/flutter/engine/tree/flutter-3.4-candidate.17); 

(2) UIWidgets 2.0 can be correctly loaded in Unity 2020 LTS (Intel) (e.g., Unity 2020.3.38f1c1 (Intel)) on a Macbook with M1 chip (e.g., Apple M1 Max, 2021 version) with the help of Rosseta.

As we are currently working on the ungrade intensively, you can use try using Rosseta + Unity (Intel) for now and wait for our later update. Thanks !
